import type { LandingFlowNode } from "@models/home-page.model";

/** Canonical playground flow — order matches the vertical diagram. */
export const LANDING_FLOW_NODES: readonly LandingFlowNode[] = [
  {
    id: "angular",
    icon: "pi pi-desktop",
    titleKey: "LANDING.FLOW.ANGULAR.TITLE",
    descKey: "LANDING.FLOW.ANGULAR.DESC",
    details: [
      { icon: "pi pi-code", labelKey: "LANDING.FLOW.ANGULAR.D1" },
      { icon: "pi pi-language", labelKey: "LANDING.FLOW.ANGULAR.D2" },
      { icon: "pi pi-palette", labelKey: "LANDING.FLOW.ANGULAR.D3" },
      { icon: "pi pi-lock", labelKey: "LANDING.FLOW.ANGULAR.D4" },
      { icon: "pi pi-shield", labelKey: "LANDING.FLOW.ANGULAR.D5" },
      { icon: "pi pi-arrows-h", labelKey: "LANDING.FLOW.ANGULAR.D6" },
      { icon: "pi pi-paperclip", labelKey: "LANDING.FLOW.ANGULAR.D7" },
      { icon: "pi pi-sliders-h", labelKey: "LANDING.FLOW.ANGULAR.D8" },
    ],
  },
  {
    id: "gateway",
    icon: "pi pi-sliders-h",
    titleKey: "LANDING.FLOW.GATEWAY.TITLE",
    descKey: "LANDING.FLOW.GATEWAY.DESC",
    details: [
      { icon: "pi pi-google", labelKey: "LANDING.FLOW.GATEWAY.D1" },
      { icon: "pi pi-key", labelKey: "LANDING.FLOW.GATEWAY.D2" },
      { icon: "pi pi-shield", labelKey: "LANDING.FLOW.GATEWAY.D3" },
      { icon: "pi pi-share-alt", labelKey: "LANDING.FLOW.GATEWAY.D4" },
      { icon: "pi pi-list", labelKey: "LANDING.FLOW.GATEWAY.D5" },
    ],
  },
  {
    id: "fastapi",
    icon: "pi pi-server",
    titleKey: "LANDING.FLOW.FASTAPI.TITLE",
    descKey: "LANDING.FLOW.FASTAPI.DESC",
    details: [
      { icon: "pi pi-play", labelKey: "LANDING.FLOW.FASTAPI.D1" },
      { icon: "pi pi-database", labelKey: "LANDING.FLOW.FASTAPI.D2" },
      { icon: "pi pi-send", labelKey: "LANDING.FLOW.FASTAPI.D3" },
      { icon: "pi pi-sync", labelKey: "LANDING.FLOW.FASTAPI.D4" },
      { icon: "pi pi-verified", labelKey: "LANDING.FLOW.FASTAPI.D5" },
      { icon: "pi pi-link", labelKey: "LANDING.FLOW.FASTAPI.D6" },
      { icon: "pi pi-list", labelKey: "LANDING.FLOW.FASTAPI.D7" },
      { icon: "pi pi-send", labelKey: "LANDING.FLOW.FASTAPI.D8" },
      { icon: "pi pi-inbox", labelKey: "LANDING.FLOW.FASTAPI.D9" },
    ],
  },
  {
    id: "file-service",
    icon: "pi pi-file",
    titleKey: "LANDING.FLOW.FILE_SERVICE.TITLE",
    descKey: "LANDING.FLOW.FILE_SERVICE.DESC",
    details: [
      { icon: "pi pi-cloud-upload", labelKey: "LANDING.FLOW.FILE_SERVICE.D1" },
      { icon: "pi pi-check", labelKey: "LANDING.FLOW.FILE_SERVICE.D2" },
      { icon: "pi pi-link", labelKey: "LANDING.FLOW.FILE_SERVICE.D3" },
      { icon: "pi pi-shield", labelKey: "LANDING.FLOW.FILE_SERVICE.D4" },
      { icon: "pi pi-download", labelKey: "LANDING.FLOW.FILE_SERVICE.D5" },
      { icon: "pi pi-send", labelKey: "LANDING.FLOW.FILE_SERVICE.D6" },
    ],
  },
  {
    id: "azure-blob",
    icon: "pi pi-cloud",
    titleKey: "LANDING.FLOW.AZURE_BLOB.TITLE",
    descKey: "LANDING.FLOW.AZURE_BLOB.DESC",
    details: [
      { icon: "pi pi-upload", labelKey: "LANDING.FLOW.AZURE_BLOB.D1" },
      { icon: "pi pi-key", labelKey: "LANDING.FLOW.AZURE_BLOB.D2" },
      { icon: "pi pi-sync", labelKey: "LANDING.FLOW.AZURE_BLOB.D3" },
    ],
  },
  {
    id: "postgres",
    icon: "pi pi-table",
    titleKey: "LANDING.FLOW.POSTGRES.TITLE",
    descKey: "LANDING.FLOW.POSTGRES.DESC",
    details: [
      { icon: "pi pi-bookmark", labelKey: "LANDING.FLOW.POSTGRES.D1" },
      { icon: "pi pi-check-square", labelKey: "LANDING.FLOW.POSTGRES.D2" },
      { icon: "pi pi-cog", labelKey: "LANDING.FLOW.POSTGRES.D3" },
    ],
  },
  {
    id: "redis",
    icon: "pi pi-chart-line",
    titleKey: "LANDING.FLOW.REDIS.TITLE",
    descKey: "LANDING.FLOW.REDIS.DESC",
    details: [
      { icon: "pi pi-inbox", labelKey: "LANDING.FLOW.REDIS.D1" },
      { icon: "pi pi-bolt", labelKey: "LANDING.FLOW.REDIS.D2" },
      { icon: "pi pi-replay", labelKey: "LANDING.FLOW.REDIS.D3" },
    ],
  },
  {
    id: "worker",
    icon: "pi pi-cog",
    titleKey: "LANDING.FLOW.WORKER.TITLE",
    descKey: "LANDING.FLOW.WORKER.DESC",
    details: [
      { icon: "pi pi-download", labelKey: "LANDING.FLOW.WORKER.D1" },
      { icon: "pi pi-sparkles", labelKey: "LANDING.FLOW.WORKER.D2" },
      { icon: "pi pi-upload", labelKey: "LANDING.FLOW.WORKER.D3" },
      { icon: "pi pi-file", labelKey: "LANDING.FLOW.WORKER.D4" },
      { icon: "pi pi-tag", labelKey: "LANDING.FLOW.WORKER.D5" },
      { icon: "pi pi-send", labelKey: "LANDING.FLOW.WORKER.D6" },
    ],
  },
  {
    id: "nats",
    icon: "pi pi-share-alt",
    titleKey: "LANDING.FLOW.NATS.TITLE",
    descKey: "LANDING.FLOW.NATS.DESC",
    details: [
      { icon: "pi pi-file", labelKey: "LANDING.FLOW.NATS.D1" },
      { icon: "pi pi-user", labelKey: "LANDING.FLOW.NATS.D2" },
      { icon: "pi pi-sparkles", labelKey: "LANDING.FLOW.NATS.D3" },
      { icon: "pi pi-inbox", labelKey: "LANDING.FLOW.NATS.D4" },
    ],
  },
  {
    id: "event-store",
    icon: "pi pi-history",
    titleKey: "LANDING.FLOW.EVENT_STORE.TITLE",
    descKey: "LANDING.FLOW.EVENT_STORE.DESC",
    details: [
      { icon: "pi pi-database", labelKey: "LANDING.FLOW.EVENT_STORE.D1" },
      { icon: "pi pi-list", labelKey: "LANDING.FLOW.EVENT_STORE.D2" },
      { icon: "pi pi-ban", labelKey: "LANDING.FLOW.EVENT_STORE.D3" },
    ],
  },
  {
    id: "ado",
    icon: "pi pi-cloud-upload",
    titleKey: "LANDING.FLOW.ADO.TITLE",
    descKey: "LANDING.FLOW.ADO.DESC",
    details: [
      { icon: "pi pi-github", labelKey: "LANDING.FLOW.ADO.D1" },
      { icon: "pi pi-list", labelKey: "LANDING.FLOW.ADO.D2" },
      { icon: "pi pi-verified", labelKey: "LANDING.FLOW.ADO.D3" },
    ],
  },
] as const;
