trigger:
  branches:
    include:
      - int

resources:
  repositories:
    - repository: master-pipelines
      type: git
      name: "DatHa Platform/master-pipelines"
      ref: refs/heads/main
variables:
  - group: pipeline-config

stages:
  - template: pipelines/angular-template.yml@master-pipelines
    parameters:
      appName: "chatbot-frontend"
      skipTest: true
      artifactTypes:
        - docker
      appShortName: "chatbot-frontend"
      terraformDir: "/IaC"
      deployToK8s: true
      environment: "int"
      buildMode: "-- --configuration integration"
