FROM node:24-alpine AS builder
ARG SOURCE="dist"
ARG TAG=0.0.1

USER root
RUN corepack enable && corepack prepare pnpm@10.33.2 --activate
WORKDIR /home
RUN mkdir appuser
WORKDIR /home/appuser
COPY --chown=appuser . .

ARG NODE_OPTIONS="--max-old-space-size=8192"
ENV NODE_OPTIONS $NODE_OPTIONS
ENV NODE_ENV=development
RUN rm -rf ./dist
RUN rm -rf ./node_modules
RUN pnpm install --frozen-lockfile
RUN pnpm exec ng build --configuration development --output-hashing none --base-href=/${TAG}/messenger-frontend/


FROM nginx:1.28.0-alpine3.21-slim
ARG TAG=0.0.1
COPY --from=builder /home/appuser/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /home/appuser/dist/messenger-frontend/index.html /usr/share/nginx/html
COPY --from=builder /home/appuser/dist/ /usr/share/nginx/html/${TAG}

EXPOSE 80
